// <auto-generated />
using System;
using JCMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JCMS.Infrastructure.Migrations
{
    [DbContext(typeof(JcmsDbContext))]
    partial class JcmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JCMS.Infrastructure.Entities.CleaningHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CleaningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JewelryItemId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JewelryItemId");

                    b.HasIndex("StaffId");

                    b.ToTable("CleaningHistory");
                });

            modelBuilder.Entity("JCMS.Infrastructure.Entities.CleaningOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConfirmationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InProgressAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StaffId");

                    b.ToTable("CleaningOrder");
                });

            modelBuilder.Entity("JCMS.Infrastructure.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("JCMS.Infrastructure.Entities.JewelryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ParentItemId");

                    b.ToTable("JewelryItems");
                });

            modelBuilder.Entity("JCMS.Infrastructure.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CleaningOrderId")
                        .HasColumnType("int");

                    b.Property<int>("JewelryItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CleaningOrderId");

                    b.HasIndex("JewelryItemId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("JCMS.Infrastructure.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("JCMS.Infrastructure.Entities.CleaningHistory", b =>
                {
                    b.HasOne("JCMS.Infrastructure.Entities.JewelryItem", "JewelryItem")
                        .WithMany("CleaningHistoryEntries")
                        .HasForeignKey("JewelryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JCMS.Infrastructure.Entities.Staff", "Staff")
                        .WithMany("CleaningHistoryEntries")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JewelryItem");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("JCMS.Infrastructure.Entities.CleaningOrder", b =>
                {
                    b.HasOne("JCMS.Infrastructure.Entities.Customer", "Customer")
                        .WithMany("CleaningOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JCMS.Infrastructure.Entities.Staff", "Staff")
                        .WithMany("CleaningOrders")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("JCMS.Infrastructure.Entities.JewelryItem", b =>
                {
                    b.HasOne("JCMS.Infrastructure.Entities.Customer", "Customer")
                        .WithMany("JewelryItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JCMS.Infrastructure.Entities.JewelryItem", "ParentItem")
                        .WithMany("ChildItems")
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("ParentItem");
                });

            modelBuilder.Entity("JCMS.Infrastructure.Entities.OrderItem", b =>
                {
                    b.HasOne("JCMS.Infrastructure.Entities.CleaningOrder", "CleaningOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("CleaningOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JCMS.Infrastructure.Entities.JewelryItem", "JewelryItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("JewelryItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CleaningOrder");

                    b.Navigation("JewelryItem");
                });

            modelBuilder.Entity("JCMS.Infrastructure.Entities.CleaningOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("JCMS.Infrastructure.Entities.Customer", b =>
                {
                    b.Navigation("CleaningOrders");

                    b.Navigation("JewelryItems");
                });

            modelBuilder.Entity("JCMS.Infrastructure.Entities.JewelryItem", b =>
                {
                    b.Navigation("ChildItems");

                    b.Navigation("CleaningHistoryEntries");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("JCMS.Infrastructure.Entities.Staff", b =>
                {
                    b.Navigation("CleaningHistoryEntries");

                    b.Navigation("CleaningOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
